name: Build packages
on: push

jobs:
  package_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make file
        run: |
          echo -e "\n$GITHUB_SHA" >> ./myscript.sh
      - name: Move file
        run: |
          mkdir scripts
          cp ./myscript.sh ./scripts/myscript.sh
      - name: Save file
        uses: actions/upload-artifact@v2
        with:
          name: My Script
          path: scripts
  test_centos:
    needs: package_job
    runs-on: ubuntu-20.04
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: scripts
      - name: Use Script in Docker
        run: |
          docker run -v $PWD/scripts/myscript.sh:/script/myscript.sh centos:7 /bin/bash -c "/script/myscript.sh Cool!"
  test_ubuntu:
    needs: package_job
    runs-on: ubuntu-20.04
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: scripts
      - name: Use Script in Docker
        run: |
          docker run -v $PWD/scripts/myscript.sh:/script/myscript.sh ubuntu:20.04 /bin/bash -c "/script/myscript.sh Cool!"
