# on: [push]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Hello world action step
#         id: hello
#         uses: ./
#         with:
#           who-to-greet: 'Babycakes'
#       # Use the output from the `hello` step
#       - name: Get the output time
#         run: echo "The time was ${{ steps.hello.outputs.time }}"

name: Build packages
on:
  push:
    branches:
      - artifact

jobs:
  package_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make file
        run: |
          echo $GITHUB_SHA >> ./myscript.sh
      - name: Save file
        uses: actions/upload-artifact@v2
        with:
          name: My Script
          path: ./myscript.sh

      - name: Use Script in Docker
        run: |
          docker run -v $PWD/myscript.sh:/script/myscript.sh centos:7 /bin/bash -c "cat /script/myscript.sh"
