name: Build packages
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  package_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump event payload
        run: |
          jq . "$GITHUB_EVENT_PATH"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build pack
        run: mkdir packages && echo "am package" >> packages/pkg_type
      - name: Save packages
        uses: actions/upload-artifact@v2
        with:
          name: pkg_type
          path: packages
